### ISSUE TITLE
Getting 503 Service Unavailable Error

### ISSUE THREAD

**Issue by parth-choudhary** [ankitpopli1891/django-autotranslate#19]
I am getting 
`urllib.error.HTTPError: HTTP Error 503: Service Unavailable`
on executing 
`python manage.py translate_messages `

Any idea what's is wrong here?

**Comment by shahraizali** [comment]
When I was Using It. It worked once perfectly. And the second time It gave me this error. Most probably due to the script make a lot of calls to google translate and google picks it up as a bot and shows the captcha as the result of request and this script is unable to get to the service resulting in error 503. I tried It on another server I have Same story worked once and after that 503. 

I think providing API key(in settings.py as mentioned in readme file) should fix the issue But I have not tested.

**Comment by likeca** [comment]
It use goslate to translate by default.
Google has updated its translation service recently with a ticket mechanism to prevent simple crawler program like goslate from accessing

**Comment by bobozar** [comment]
@shahraizali @likeca what is the way forward? How do you manage to solve this?

**Comment by shahraizali** [comment]
Assalamualaikum (Hi) @bobozar !

For me translating is something which is done rarely. This system allows one command everyday like if you ran the command today then it will start giving this error for almost 24 hours but after that, it will run once again(due to google blacklisting the ip for some hours). mostly I run it after everything is complete and make sure that I don't have to run it soon . but if I have to do it within 24 hours I push the code to a staging server then run the command there. (the ultimate goal is to hit the api with different ip). This is my finding. I guess there would be alot better ways/solutions, this is what I do. If you find something interesting please do let everyone know.

Thanks

**Comment by likeca** [comment]
We can add one more engine use google translate web service.
I did modify your code on my end, the only issue is when translating the long paragraph, it will cut only translate the first sentence.

url = 'https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl={}&&dt=t&q={}'.format('zh', 'hello world!')
